mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import view

urlpatterns = [
    url(r'^$', view.index),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),

]

polls/urls.py
from django.conf.urls import url
from polls import views,search,search2
from TestModel import testdb

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^index/$', views.IndexView.as_view(), name='index1'),

    url(r'^register/$', views.register, name='register'),

    url(r'^login/$', views.login, name='login'),

    url(r'^logout/$', views.logout, name='logout'),

    url(r'^input/$', views.form_input, name='input'),

    url(r'^testdb/$',testdb.testdb,name='testdb'),

    url(r'^search/$',search.search,name='search'),

    url(r'^search-post/$', search2.search_post, name='search-post'),

    url(r'^search_form/$', search.search_form, name='search_form'),

    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(),name='detail'),

    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultView.as_view(),name='results'),

    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

TestModel/models.py
from django.db import models

# Create your models here.

class Test(models.Model):
    name = models.CharField(max_length=200)

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import AbstractUser


# import time
# Create your models here.
question_type =(('python','python编程'),
                ('sql','sql数据库'),
                ('java', 'java编程'),
                )


class Question(models.Model):
    id = models.AutoField(primary_key=True)
    question_text = models.CharField("问题描述",max_length=200)
    question_type = models.CharField("问题类型",max_length=200,choices=question_type,default=question_type[0])
    pub_date = models.DateTimeField("发布时间",default=timezone.now)
    author = models.CharField("提交人",max_length=100,null=True,blank=False)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=5) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently!'

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class CommBase(models.Model):
    # id = models.AutoField()
    user_name = models.CharField(max_length=200)
    content = models.CharField(max_length=300)
    pub_date = models.DateField()

    class Meta:
        abstract = True


TYPES = (('x1', 'xxx'),)


class Member(CommBase):
    user_type = models.CharField(max_length=20,choices=TYPES)


class User(models.Model):
    username = models.CharField(max_length=300,blank=False)
    password = models.CharField(max_length=50,blank=False)
    email = models.CharField(max_length=100,blank=False)

polls/forms.py
from django.forms import ModelForm
from polls.models import Question
from django import forms


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'


class UserRegisterForm(forms.Form):
    username = forms.CharField(label='用户名',max_length=100)
    password = forms.CharField(label='密码',widget=forms.PasswordInput(),max_length=100)
    email = forms.CharField(label='电子邮件')


class UserLoginForm(forms.Form):
    username = forms.CharField(label='用户名：',max_length=100)
    password = forms.CharField(label='密码：',widget=forms.PasswordInput())

TestModel/views.py
from django.shortcuts import render

# Create your views here.

polls/views.py
from django.shortcuts import render,get_object_or_404,render_to_response
from django.http import HttpResponseRedirect,HttpResponse
from .models import Question,Choice
from django.urls import reverse
from django.views import generic
from polls.forms import QuestionForm,UserRegisterForm,UserLoginForm
from polls.models import User
from django.contrib.auth.decorators import login_required
import os
from django.contrib import auth


def register(request):
    if request.method == 'POST':
        uf = UserRegisterForm(request.POST)
        if uf.is_valid():
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            email = uf.cleaned_data['email']

            user = User()
            user.username = username
            user.password = password
            user.email = email
            user.save()
            return render_to_response('polls/register_success.html',{'username': username})
    else:
        uf = UserRegisterForm()
    return render_to_response('polls/register.html',{'uf':uf})


def login(request):
    if request.method == 'POST':
        uf = UserLoginForm(request.POST)
        if uf.is_valid():
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            user = auth.authenticate(username__exact=username,password__exact=password)
            if user:
                return render_to_response('polls/login_success.html',{'username':username})
            else:
                return HttpResponseRedirect('/polls/login/')
    else:
        uf = UserLoginForm()
    return render_to_response('polls/login.html',{'uf':uf})


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/polls/login/')


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question': question, 'error_message': "do not select a choice", })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:6]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


@login_required
def form_input(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            Question = form.save()
            Question.save()
            return HttpResponseRedirect(reverse("polls:index"))
    else:
        form = QuestionForm()
    FILE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return render(request, os.path.join(FILE_ROOT, 'polls/templates/polls','input.html'),{'form':form})

polls/templates/polls/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>修改密码</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
        <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h1><a href="{% url 'index' %}">Django Auth Example</a></h1>
                <h3>修改密码</h3>
                <form class="form" action="{% url 'polls:change_password' %}" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">确认修改</button>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

polls/templates/polls/change_psd_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>密码修改成功</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div>
            <h1 class="logo"><a href="{% url 'index' %}">Django Auth Example</a></h1>
            <p>密码修改成功！</p>
        </div>
    </div>
</div>
</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>

</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>问题列表展示</title>
</head>
{#<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />#}
<body>
<div>
<h1 style="color: #5c79dc">王雯璐超级超级漂亮！！！！！！！！！！</h1>

<h2 align="center" style="color: darkviolet">王雯璐超级超级超级可爱！！！！！！！！！！</h2>
</div>
<div>
    {% if latest_question_list %}
        <ul>
            <p>王雯璐超级超级漂亮！！！！！！！！！！</p>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                <a>{{ question.author }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are avalible....</p>
    {% endif %}
</div>
<div>
    <a href="{% url 'polls:input' %}"> 输入问题 </a>
</div>

<div>
    <tbody>
            <tr><th>问题描述    </th>  <th>问题类型 </th>  <th>提出人  </th>
            </tr>

    </tbody>
</div>


</body>

polls/templates/polls/input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>问题录入界面</title>
</head>
<body>
        <form action="?" method="post">
            <fieldset>
                <legend>请输入并且提交内容</legend>
                 {{ form.as_p }}
                <input type="submit" value="submit" />
            </fieldset>
        </form>
</body>
</html>

polls/templates/polls/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>登录</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>

<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h3>登录</h3>
                <form class="form" action="{% url 'polls:login' %}" method="post">
                    {% csrf_token %}
                    {{ uf.non_field_errors }}
                    {% for field in uf %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }} </p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">登录</button>
                    <input type="hidden" name="next" value="{{ next }}"/>
                </form>
                <div class="flex-left top-gap text-small">
                    <div class="unit-2-3"><span>没有账号？<a href="{% url 'polls:register' %}">立即注册</a></span></div>
                     <div class="unit-1-3 flex-right"><span><a href="reset_password.html">忘记密码？</a></span></div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

polls/templates/polls/login_bak.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<style>
    body{color: #efd;background: #453;padding: 0 5em;margin: 0}
    h1{padding: 2em 1em;background: #675
    h2{color: #bf8;border-top: 1px dotted #fff;margin-top: 2em}
    p{margin: 1em 0}
</style>
<body>
<h1>登录页面</h1>
<form method="post" enctype="multipart/form-data">
    {{ uf.as_p }}
    <input type="submit" value="ok" />
</form>

</body>
</html>

polls/templates/polls/login_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>恭喜{{ username }},登录成功！</h1>
</body>
</html>

polls/templates/polls/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>h {{username}} !</h1>
<br>
<a href="http://127.0.0.1:8000/online/logout/">退出</a>
</body>
</html>

polls/templates/polls/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="/polls/search-post/" method="post">
        {% csrf_token %}
        <input type="text" name="q">
        <input type="submit" value="submit">
        <p>{{ rlt }}</p>
    </form>
</body>
</html>

polls/templates/polls/register_bak.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
</head>
    <style type="text/css">
    body{color: #efd;background: #453;padding: 0 5em;margin: 0}
        h1{padding: 2em 1em;background: #675}
        h2{color: #bf8;border-top: 1px dotted #fff;margin-top: 2em}
        p{margin: 1em 0}
    </style>
<body>
    <h1>注册页面：</h1>
<form method="post" enctype="multipart/form-data">
    {{ uf.as_p }}
    <input type="submit" value="ok"/>
</form>
</body>
</html>

polls/templates/polls/register_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>恭喜{{username}}，注册成功！</h1>
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_txt }} -- {{ choice.votes }} vote {{ choice.votes|pluralize }}</li>
    {% endfor %}
    
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{#</body>#}
{#</html>#}

polls/templates/polls/search_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>表单测试</title>
</head>
<body>
    <form action="/polls/search" method="get">
        <input type="text" name="q">
        <input type="submit" value="搜索">
    </form>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is a test</title>
    <h1>{{ test }}</h1>
</head>
<body>
<div>
{% if user.is_authenticated %}
    <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
      <button class="btn btn-default"><a href="{% url 'polls:logout' %}?next={{ request.path }}">注销登录</a></button>
{% else %}
  <p>你还没有登录，请
    <button class="btn btn-default"><a href="{% url 'polls:login' %}?next={{ request.path }}">登录</a></button>
    或者
    <button class="btn btn-default"><a href="{% url 'polls:register' %}">注册</a></button>
    <button class="btn btn-default"><a href="{% url 'polls:change_password' %}?next={{ request.path }}">修改密码</a></button>
  </p>
{% endif %}
</div>

</body>
</html>

templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
    <h1 style="background-color:antiquewhite;color:black;"> hello world</h1>

    <h1 style="...">用户输入：</h1>
    <form action="/index/" method="post">
        <input type="text" name="username"/>
        <input type="password" name="password"/>
        <input type="submit" value="提交"/>
    </form>
    <hr/>
    <h1 style="...">用户展示：</h1>
    <table border="1">
        <thead>
            <th>用户名</th>
            <th>密码</th>
        </thead>
        <tbody>
                {% for line in data %}
                    <tr>
                        <td>{{ line.user }}</td>
                        <td>{{ line.pwd }}</td>
                    </tr>
                {% endfor %}
        </tbody>
    </table>


    <script src="/static/js/jquery.js"></script>
</body>
</html>